CREATE TABLE contributor_stats (
    repo VARCHAR(255),
    contributor_name VARCHAR(255),
    contributor_username VARCHAR(255),
    curved_score FLOAT,
    stats_beginning DATE,
    stats_ending DATE,
    contributor_first_commit_date DATE,
    num_workdays INT,
    commits INT,
    prs INT,
    review_comments INT,
    changed_lines INT,
    avg_pr_duration FLOAT,
    avg_code_movement_per_pr FLOAT,
    commits_per_day FLOAT,
    changed_lines_per_day FLOAT,
    prs_per_day FLOAT,
    review_comments_per_day FLOAT,
    prs_diff_from_mean FLOAT, 
    prs_ntile INT,
    commits_ntile INT,
    lines_of_code_ntile INT,
    review_comments_ntile INT,
    avg_pr_duration_ntile INT,
    avg_ntile INT
);
